// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Settl.Api.Data;

#nullable disable

namespace Settl.Api.Migrations
{
    [DbContext(typeof(SettlDbContext))]
    partial class SettlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Settl.Api.Domain.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FromMemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaidByMemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecurringTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SplitMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("RecurringTemplateId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_Entry_RecurringTemplate_Date");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Settl.Api.Domain.EntryShare", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FormulaValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("ShareMinor")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("EntryShares");
                });

            modelBuilder.Entity("Settl.Api.Domain.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("SEK");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("Settl.Api.Domain.HouseholdMembership", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("HouseholdId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("HouseholdMemberships");
                });

            modelBuilder.Entity("Settl.Api.Domain.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Settl.Api.Domain.RecurringShare", b =>
                {
                    b.Property<Guid>("RecurringTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FormulaValue")
                        .HasColumnType("TEXT");

                    b.HasKey("RecurringTemplateId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("RecurringShares");
                });

            modelBuilder.Entity("Settl.Api.Domain.RecurringTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("NextPostDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaidByMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SplitMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("RecurringTemplates");
                });

            modelBuilder.Entity("Settl.Api.Domain.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitiatedByMemberId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SettledAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Settlements");
                });

            modelBuilder.Entity("Settl.Api.Domain.SettlementClosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreditorMemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DebtorMemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.HasIndex("EntryId", "DebtorMemberId", "CreditorMemberId")
                        .IsUnique()
                        .HasDatabaseName("IX_SettlementClosure_Entry_Debtor_Creditor");

                    b.ToTable("SettlementClosures");
                });

            modelBuilder.Entity("Settl.Api.Domain.Entry", b =>
                {
                    b.HasOne("Settl.Api.Domain.Household", "Household")
                        .WithMany("Entries")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settl.Api.Domain.RecurringTemplate", "RecurringTemplate")
                        .WithMany("PostedEntries")
                        .HasForeignKey("RecurringTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Household");

                    b.Navigation("RecurringTemplate");
                });

            modelBuilder.Entity("Settl.Api.Domain.EntryShare", b =>
                {
                    b.HasOne("Settl.Api.Domain.Entry", "Entry")
                        .WithMany("Shares")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settl.Api.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Settl.Api.Domain.HouseholdMembership", b =>
                {
                    b.HasOne("Settl.Api.Domain.Household", "Household")
                        .WithMany("Memberships")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Settl.Api.Domain.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Settl.Api.Domain.RecurringShare", b =>
                {
                    b.HasOne("Settl.Api.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Settl.Api.Domain.RecurringTemplate", "RecurringTemplate")
                        .WithMany("Shares")
                        .HasForeignKey("RecurringTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("RecurringTemplate");
                });

            modelBuilder.Entity("Settl.Api.Domain.RecurringTemplate", b =>
                {
                    b.HasOne("Settl.Api.Domain.Household", "Household")
                        .WithMany("RecurringTemplates")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Settl.Api.Domain.Settlement", b =>
                {
                    b.HasOne("Settl.Api.Domain.Household", "Household")
                        .WithMany("Settlements")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Settl.Api.Domain.SettlementClosure", b =>
                {
                    b.HasOne("Settl.Api.Domain.Entry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Settl.Api.Domain.Settlement", "Settlement")
                        .WithMany("Closures")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("Settl.Api.Domain.Entry", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("Settl.Api.Domain.Household", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Memberships");

                    b.Navigation("RecurringTemplates");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("Settl.Api.Domain.Member", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Settl.Api.Domain.RecurringTemplate", b =>
                {
                    b.Navigation("PostedEntries");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("Settl.Api.Domain.Settlement", b =>
                {
                    b.Navigation("Closures");
                });
#pragma warning restore 612, 618
        }
    }
}
